"""Data contracts. Defined once, consumed by CLI, API and front-end.

These models are the shared vocabulary between modules that never import each
other: retrieval.py knows nothing about generate.py, but both speak
RetrievedChunk. They also guard the boundaries -- Evaluation in particular,
because the judge's JSON is generated by a language model and cannot be
trusted to respect its own schema.
"""
from pydantic import BaseModel, Field


class Chunk(BaseModel):
    """A segment of the source document, as produced by the indexing pipeline."""

    chunk_id: int
    text: str
    section: str
    n_tokens: int
    char_start: int
    char_end: int


class RetrievedChunk(BaseModel):
    """A chunk returned for one question, with its score against that question.

    Deliberately NOT a subclass of Chunk: n_tokens and the char offsets are
    indexing bookkeeping and must never reach the API response.
    """

    chunk_id: int
    section: str
    score: float
    text: str


class RagResponse(BaseModel):
    """Exactly three top-level keys. Nothing else is ever added here.

    The evaluator's verdict is nested under a wrapper by the caller
    ({"response": ..., "evaluation": ...}), never as a fourth key.
    """

    user_question: str
    system_answer: str
    chunks_related: list[RetrievedChunk]


class Evaluation(BaseModel):
    """The judge's verdict. The constraints are the point of this model."""

    score: int = Field(ge=0, le=10)
    reason: str = Field(min_length=50)


class IndexMeta(BaseModel):
    """Index provenance. embedding_model is what load_index() checks before
    letting a query run against vectors built by a different model."""

    embedding_model: str
    dimension: int
    n_chunks: int
    chunk_size: int
    overlap: int
    normalized: bool
    source_file: str
    source_sha256: str
    created_at: str
